### ISSUE TITLE
add image to home page 

### ISSUE THREAD

**Issue by j-mrles** [j-mrles/DjangoRestaurant#11]
![Screenshot 2024-10-31 at 3 49 39 PM](https://github.com/user-attachments/assets/b557d826-7704-40fe-9845-a3c4811f1e98)

this page as well as others are missing image pls add so it or anything similar so it  is UI friendly

**Comment by levisessions** [comment]
![image](https://github.com/user-attachments/assets/028e717c-ff4c-4ab3-98d9-528993d2e19d)
Image added by Javier, included in main
