### ISSUE TITLE
Reservation Page CSS 

### ISSUE THREAD

**Issue by j-mrles** [j-mrles/DjangoRestaurant#21]
![Screenshot 2024-11-02 at 2 46 37 PM](https://github.com/user-attachments/assets/1f77d0ab-5b57-493e-8fc3-b853564a051d)
![Screenshot 2024-10-31 at 4 03 08 PM](https://github.com/user-attachments/assets/72121c79-8cf3-43bb-8c1f-3a5ae6178211)

- add css so it matches figma mock up for the make reservation and already have a reservation section

**Comment by levisessions** [comment]
![image](https://github.com/user-attachments/assets/1f6dc2d5-4a04-4ed3-9466-25cd61ef5bc3)

Working in main
