### ISSUE TITLE
Login Message

### ISSUE THREAD

**Issue by j-mrles** [j-mrles/DjangoRestaurant#47]
<img width="685" alt="Screenshot 2024-11-12 at 10 32 41 AM" src="https://github.com/user-attachments/assets/3de2fdc7-9fe8-4e89-ae77-8926c86ced0a">

When loading the project, there is a bug that displays the "user is logged", "not logged in" or "user not authorized!" before even attempting to login, fix the bug

**Comment by gabe-vega** [comment]
As far as I can see, the changes I've made are preventing messages from appearing at inappropriate times.

**Comment by gabe-vega** [comment]
Ready to be pulled
