### ISSUE TITLE
Edited: Bug fixes and modify/remove reservation

### ISSUE THREAD

**Issue by gabe-vega** [j-mrles/DjangoRestaurant#68]
will need support for this issue, but the role of the user needs to be more well defined both in what we think they should be able to do and in what they can and cannot do in the system itself

**Comment by levisessions** [comment]
Superusers used for true administrative purposes (debugging basically), accounts set to Staff through the admin portal can see the View All Reservations page, Regular users (without the staff flag) can make reservations and view the reservations associated with their account on the Make Reservation page. Users who are not logged in instead see the option to search for their reservation(s).

**Comment by gabe-vega** [comment]
fixed small issue where making a reservation successfully would send user to home page instead of the confirmation page

**Comment by gabe-vega** [comment]
fixed issue where confirmation page would not show user info

**Comment by gabe-vega** [comment]
- error as of next commit, guest cannot make reservation

**Comment by gabe-vega** [comment]
- fixed issue where making reservation at 10 would cause error (with the current table availability logic, loop checks for two hours ahead of reservation time, and 10 is 22:00, so it didn't like 24:00)

**Comment by gabe-vega** [comment]
- issue change: from small issue to large change
- guests can now make reservations (with their usernames being a generated number)
     - may need to revisit; for times when names are displayed, guests have no name to display (like in view all, there is no name associated with res, maybe sub with email?, but then they're not really guests because their info is stored??)
- added html for checking in, modifying, and removing a reservation
- added views/urls for modifying and removing a reservation
- added some checks in table availability function to convert incoming time to a datetime object if it was a string

**Comment by gabe-vega** [comment]
- All commits made, but please watch for .gitignore coming from this branch/another branch. On my branch, it has *, which meant i had to manually add each (html and css) file, and I don't remember it ignoring everything. Might not be a problem.
